{
 "title": "ECS 3.2 Geo-Replication",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "VDC",
    "label": "VDC",
    "query": "SHOW TAG VALUES WITH KEY = \"VDC\""
   },
   {
    "name": "RG",
    "label": "Replication Group",
    "query": "SHOW TAG VALUES WITH KEY = \"ReplicationGroupID\""
   }
  ]
 },
 "panels": [
  { "title": "Bootstrap Processing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Bootstrap Progress (%)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_ReplicationGroupID",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ReplicationGroupID" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LocalZoneReplicationBootstrap",
     "select": [
      [
       { "params": [ "BootstrapProgressPercent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "VDC", "operator": "=~", "value": "/^$VDC$/" },
      { "condition": "AND", "key": "ReplicationGroupID", "operator": "=~", "value": "/^$RG$/" }
     ]
    }
   ]
  },
  {
   "title": "Data Pending Bootstrap Replication",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Meta Data: $tag_ReplicationGroupID",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ReplicationGroupID" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LocalZoneReplicationBootstrap",
     "select": [
      [
       {
        "params": [
         "chunksJournalPendingBootstrapReplicationTotalSize"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "VDC", "operator": "=~", "value": "/^$VDC$/" },
      { "condition": "AND", "key": "ReplicationGroupID", "operator": "=~", "value": "/^$RG$/" }
     ]
    },
    {
     "alias": "User Data: $tag_ReplicationGroupID",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ReplicationGroupID" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LocalZoneReplicationBootstrap",
     "select": [
      [
       {
        "params": [
         "chunksRepoPendingBootstrapReplicationTotalSize"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "VDC", "operator": "=~", "value": "/^$VDC$/" },
      { "condition": "AND", "key": "ReplicationGroupID", "operator": "=~", "value": "/^$RG$/" }
     ]
    }
   ]
  },
  {
   "title": "Replication Rates and Overall RPO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 }
  },
  {
   "title": "Recover Point Objective (RPO)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "dateTimeAsIso" }
   ],
   "targets": [
    {
     "alias": "$tag_ReplicationGroupID",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "VDC" ], "type": "tag" },
      { "params": [ "ReplicationGroupID" ], "type": "tag" }
     ],
     "measurement": "LocalZoneReplication",
     "select": [
      [
       { "params": [ "replicationRpoTimestamp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "VDC", "operator": "=~", "value": "/^$VDC$/" },
      { "condition": "AND", "key": "ReplicationGroupID", "operator": "=~", "value": "/^$RG$/" }
     ]
    }
   ]
  },
  {
   "title": "Replication Ingress Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_ReplicationGroupID",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ReplicationGroupID" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LocalZoneReplicationMetrics",
     "select": [
      [
       {
        "params": [
         "replicationIngressTrafficCurrent"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "VDC", "operator": "=~", "value": "/^$VDC$/" },
      { "condition": "AND", "key": "ReplicationGroupID", "operator": "=~", "value": "/^$RG$/" }
     ]
    }
   ]
  },
  {
   "title": "Replication Egress Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_ReplicationGroupID",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ReplicationGroupID" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LocalZoneReplicationMetrics",
     "select": [
      [
       {
        "params": [
         "replicationEgressTrafficCurrent"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "VDC", "operator": "=~", "value": "/^$VDC$/" },
      { "condition": "AND", "key": "ReplicationGroupID", "operator": "=~", "value": "/^$RG$/" }
     ]
    }
   ]
  },
  { "title": "Chunks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Meta-Data Pending Replication",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_ReplicationGroupID",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ReplicationGroupID" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LocalZoneReplication",
     "select": [
      [
       {
        "params": [
         "chunksJournalPendingReplicationTotalSize"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "VDC", "operator": "=~", "value": "/^$VDC$/" },
      { "condition": "AND", "key": "ReplicationGroupID", "operator": "=~", "value": "/^$RG$/" }
     ]
    }
   ]
  },
  {
   "title": "User-Data Pending Replication",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_ReplicationGroupID",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ReplicationGroupID" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LocalZoneReplication",
     "select": [
      [
       {
        "params": [
         "chunksRepoPendingReplicationTotalSize"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "VDC", "operator": "=~", "value": "/^$VDC$/" },
      { "condition": "AND", "key": "ReplicationGroupID", "operator": "=~", "value": "/^$RG$/" }
     ]
    }
   ]
  },
  {
   "title": "Data Pending XOR",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_ReplicationGroupID",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ReplicationGroupID" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LocalZoneReplication",
     "select": [
      [
       { "params": [ "chunksPendingXorTotalSize" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "VDC", "operator": "=~", "value": "/^$VDC$/" },
      { "condition": "AND", "key": "ReplicationGroupID", "operator": "=~", "value": "/^$RG$/" }
     ]
    }
   ]
  }
 ]
}