{
 "title": "ECS 3.2 Health Monitoring",
 "time": { "from": "2018-07-08T19:54:11.433Z", "to": "2018-07-16T19:46:11.433Z" },
 "templating": {
  "list": [
   {
    "name": "VDC",
    "label": "VDC",
    "query": "SHOW TAG VALUES WITH KEY = \"VDC\""
   },
   {
    "name": "Node",
    "label": "Node",
    "query": "SHOW TAG VALUES WITH KEY = \"NodeID\""
   }
  ]
 },
 "panels": [
  { "title": "Disk and Node Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Nodes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LocalZone",
     "select": [
      [
       { "params": [ "numNodes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Good Nodes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LocalZone",
     "select": [
      [
       { "params": [ "numGoodNodes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bad Nodes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LocalZone",
     "select": [
      [
       { "params": [ "numBadNodes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Maint Nodes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LocalZoneNodes",
     "select": [
      [
       { "params": [ "numMaintenanceDisks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total #  of Disks",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LocalZone",
     "select": [
      [
       { "params": [ "numDisks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Good Disks",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LocalZone",
     "select": [
      [
       { "params": [ "numDisks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bad Disks",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LocalZone",
     "select": [
      [
       { "params": [ "numBadDisks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "# Maint Disks",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LocalZone",
     "select": [
      [
       { "params": [ "numMaintenanceDisks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Disk Status by Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Good Disks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_NodeID",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "NodeID" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LocalZoneNodes",
     "select": [
      [
       { "params": [ "numGoodDisks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "VDC", "operator": "=~", "value": "/^$VDC$/" },
      { "condition": "AND", "key": "NodeID", "operator": "=~", "value": "/^$Node$/" }
     ]
    }
   ]
  },
  {
   "title": "Bad Disks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_NodeID",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "NodeID" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LocalZoneNodes",
     "select": [
      [
       { "params": [ "numBadDisks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "VDC", "operator": "=~", "value": "/^$VDC$/" },
      { "condition": "AND", "key": "NodeID", "operator": "=~", "value": "/^$Node$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU and Memory Utilization by Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }
  },
  {
   "title": "Node CPU Utilization (%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_NodeID",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "NodeID" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LocalZoneNodesMetrics",
     "select": [
      [
       { "params": [ "nodeCpuUtilizationCurrent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "VDC", "operator": "=~", "value": "/^$VDC$/" },
      { "condition": "AND", "key": "NodeID", "operator": "=~", "value": "/^$Node$/" }
     ]
    }
   ]
  },
  {
   "title": "Node Memory Utilization (%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_NodeID",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "NodeID" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LocalZoneNodesMetrics",
     "select": [
      [
       { "params": [ "nodeMemoryUtilizationCurrent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "VDC", "operator": "=~", "value": "/^$VDC$/" },
      { "condition": "AND", "key": "NodeID", "operator": "=~", "value": "/^$Node$/" }
     ]
    }
   ]
  },
  { "title": "NIC Utilization by Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Node NIC Received Utilization (%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_NodeID",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "NodeID" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LocalZoneNodesMetrics",
     "select": [
      [
       {
        "params": [
         "nodeNicReceivedUtilizationCurrent"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "VDC", "operator": "=~", "value": "/^$VDC$/" },
      { "condition": "AND", "key": "NodeID", "operator": "=~", "value": "/^$Node$/" }
     ]
    }
   ]
  },
  {
   "title": "Node NIC Transmitted Utilization (%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_NodeID",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "NodeID" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LocalZoneNodesMetrics",
     "select": [
      [
       {
        "params": [
         "nodeNicTransmittedUtilizationCurrent"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "VDC", "operator": "=~", "value": "/^$VDC$/" },
      { "condition": "AND", "key": "NodeID", "operator": "=~", "value": "/^$Node$/" }
     ]
    }
   ]
  }
 ]
}